// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADK_Xxmkq9hXrU8v0uY_WobXqXVXJR3xY',
    appId: '1:440948367961:android:6670e378eef7c85af10748',
    messagingSenderId: '440948367961',
    projectId: 'flexisense',
    databaseURL: 'https://flexisense-default-rtdb.firebaseio.com',
    storageBucket: 'flexisense.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADPiRKW9gpl4Fmtta6D8mwivOIf0GunMk',
    appId: '1:440948367961:ios:ef3543202f144596f10748',
    messagingSenderId: '440948367961',
    projectId: 'flexisense',
    databaseURL: 'https://flexisense-default-rtdb.firebaseio.com',
    storageBucket: 'flexisense.appspot.com',
    androidClientId: '440948367961-38s0gslcuaiss7f5f8iec825pvip4a9m.apps.googleusercontent.com',
    iosClientId: '440948367961-0u8mcglfvfjbibo70nkol6rehj9l26rk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flexiSenseCompanion',
  );
}
